# Generated by Django 4.2.4 on 2023-08-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('is_create_role', models.BooleanField(blank=True, default=False, verbose_name='Create role')),
                ('is_update_role', models.BooleanField(blank=True, default=False, verbose_name='Assign role')),
                ('is_assign_role', models.BooleanField(blank=True, default=False, verbose_name='Assign role')),
                ('is_remove_role', models.BooleanField(blank=True, default=False, verbose_name='Assign role')),
            ],
            options={
                'verbose_name': "Account's role",
                'verbose_name_plural': "Account's roles",
            },
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accountrole'),
        ),
    ]
