# Generated by Django 4.2.4 on 2023-08-03 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountrole_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='data_joined',
        ),
        migrations.AddField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of joined'),
        ),
    ]
