# Generated by Django 4.2.4 on 2023-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_data_joined_account_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrole',
            name='is_remove_role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Remove role'),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='is_update_role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Update role'),
        ),
    ]
