# Generated by Django 4.2.4 on 2023-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_accountrole_is_assign_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrole',
            name='is_assign_role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Assign role'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='is_create_role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Create role'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='is_remove_issue',
            field=models.BooleanField(blank=True, default=False, verbose_name='Remove issue'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='is_remove_role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Remove role'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='is_update_issue',
            field=models.BooleanField(blank=True, default=False, verbose_name='Update issue'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='is_update_role',
            field=models.BooleanField(blank=True, default=False, verbose_name='Update role'),
        ),
    ]
