# Generated by Django 4.2.4 on 2023-08-03 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='subtitle')),
                ('content', models.TextField(max_length=5000, verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue/image/', verbose_name='image')),
                ('date_published', models.DateField(default=django.utils.timezone.now, verbose_name='date of published')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
